<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>amber</string>
	</array>
	<key>name</key>
	<string>Amber</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^(\s*)//</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>comment.block.amber</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.amber.function</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function-amber-general</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function-amber-condition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function-amber-iteration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function-amber-mixin-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function-amber-mixin-call</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.amber.expression</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#literal-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-amber</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(\$[a-zA-Z_\-\.]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.amber</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>meta.amber.variable</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#literal-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([\#\.][a-zA-Z0-9_\-\.]+)\s+(\?)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.amber</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>meta.amber.condition.attribute</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#literal-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.html.elemnt</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-html-element</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>meta.html.attribute</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-html-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-amber</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>function-amber-argment</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.amber.function.argment</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.+?</string>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</array>
		</dict>
		<key>function-amber-condition</key>
		<dict>
			<key>begin</key>
			<string>^\s*(if|else if|else)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.amber</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>meta.amber.function.condition</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#literal-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
		<key>function-amber-general</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.amber</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(doctype|!!!|extends|block|import)</string>
			<key>name</key>
			<string>meta.amber.function.general</string>
		</dict>
		<key>function-amber-iteration</key>
		<dict>
			<key>begin</key>
			<string>^\s*(each).+?(in)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.amber</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.amber</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>meta.amber.function.iteration</string>
		</dict>
		<key>function-amber-mixin-call</key>
		<dict>
			<key>begin</key>
			<string>^\s*(\+[a-zA-Z0-9_\-]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.amber</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>meta.amber.function.mixin.call</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#literal-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
		<key>function-amber-mixin-definition</key>
		<dict>
			<key>begin</key>
			<string>^\s*(mixin)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.amber</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>meta.amber.function.mixin.definition</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function-amber-argment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
		<key>literal-operators</key>
		<dict>
			<key>match</key>
			<string>(==|&gt;=|&lt;=|!=|=|\+|\-|%|\*|\/|\?|&amp;&amp;|\|\|)</string>
			<key>name</key>
			<string>keyword.operator.amber</string>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single</string>
		</dict>
		<key>tag-html-attribute</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.html</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([a-zA-Z\-:]+)(=?)</string>
			<key>name</key>
			<string>meta.html.attribute.name</string>
		</dict>
		<key>tag-html-element</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(abbr|address|area|article|aside|audio|a|base|bdi|bdo|blockquote|body|br|button|b|canvas|caption|cite|code|colgroup|col|data|datalist|dd|del|dfn|div|dl|dt|embed|em|fieldset|figcaption|figure|footer|form|h[1-6]|header|head|hr|html|iframe|img|input|ins|i|kbd|keygen|label|legend|link|li|main|MathML|map|mark|meta|meter|nav|noscript|object|ol|optgroup|option|output|p|param|pre|progress|q|rb|rp|rt|rtc|ruby|samp|script|section|select|small|source|span|strong|style|sub|sup|svg|s|table|tbody|td|template|textarea|tfoot|thead|th|time|title|tr|track|ul|u|var|video|wbr)</string>
			<key>name</key>
			<string>meta.html.element.name</string>
		</dict>
		<key>variable-amber</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.amber</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\$[a-zA-Z_\-\.]+)</string>
			<key>name</key>
			<string>meta.amber.variable</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.amber</string>
	<key>uuid</key>
	<string>cab3e23f-e508-40be-bef3-09d520647c0e</string>
</dict>
</plist>
